version: '3.8'

services:
  mysql:
    image: mysql:8.0  # You can choose another version of MySQL if needed
    container_name: matryriska-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set your root password
      MYSQL_DATABASE: matryriska         # This creates the database on startup
      MYSQL_USER: matryriska             # Optional: Set up an additional user
      MYSQL_PASSWORD: StrongPassword123  # Optional: Set a password for the user
    volumes:
      - mysql_data:/var/lib/mysql        # Persist MySQL data
    ports:
      - "3306:3306"                      # Expose MySQL port

  web:
    image: ghcr.io/sn0walice/matryriska:latest
    ports:
      - "8080:8080"

volumes:
  mysql_data:
